### ISSUE TITLE
pushing docker images that havent changed

### ISSUE THREAD

**Issue by smileatom** [instructure/dockerfiles#4]
Why is instructure/dynamodb latest tag being updated when the dockerfile hasnt changed?
I see this tag updating but I cant see why.  It makes it difficult to track why something was updated.
I would like to see that tags are only updated when content has actually changed.

**Comment by FreedomBen** [comment]
@rendion my guess is that it is probably getting rebuilt because one its parent images changed.

**Comment by smileatom** [comment]
Im sure you are right, but I created the issue because in a controlled environment with versioned assets, a tag shouldnt be changing without a release.  This is (not getting on a high horse), basic release semantics.  

While its great that instructure provides this docker image on dockerhub, I also think that it should respect CI/CD processes and best practices as it regards to software releases.

Otherwise docker pull becomes a question mark with no answer when dealing with stable ecosystems of docker images.

If I was a build engineer (which Im not), I would ban Docker:Latest tags which had no change to the dockerfile, without release notes as to why.

This is why docker hub links to github in the first place.

**Comment by tierra** [comment]
I actually haven't even seen a way to disable this, but with automated Docker Hub image builds (as we're using), when the base image for any of these (i.e. `ubuntu`) is updated, all downstream images trigger a new build based on that upstream build. This is actually ideal since otherwise, we aren't really notified when security updates are applied to that base image.
